# Generated by Django 3.0.7 on 2020-06-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adserver', models.CharField(blank=True, max_length=30)),
                ('blocking', models.BooleanField()),
                ('markup', models.CharField(max_length=10000)),
                ('screenshot_url', models.URLField(blank=True)),
            ],
        ),
    ]
