# Generated by Django 3.0.7 on 2020-06-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creative',
            name='markup',
            field=models.TextField(),
        ),
    ]
