# Generated by Django 3.0.7 on 2020-06-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0002_auto_20200609_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='blocking_vendor',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
