# Generated by Django 3.0.7 on 2020-06-10 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creative_groups', '0001_initial'),
        ('creatives', '0003_creative_blocking_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='creative_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='creative_groups.CreativeGroup'),
            preserve_default=False,
        ),
    ]
