# Generated by Django 3.0.7 on 2020-06-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0004_creative_creative_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creative',
            old_name='creative_group',
            new_name='creative_group_id',
        ),
    ]
