# Generated by Django 3.0.7 on 2020-06-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0005_auto_20200610_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='screenshot',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
