# Generated by Django 3.0.7 on 2020-06-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0008_auto_20200610_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='markup_without_blocking',
            field=models.TextField(blank=True),
        ),
    ]
