# Generated by Django 3.0.7 on 2020-06-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0009_creative_markup_without_blocking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creative',
            name='blocking',
            field=models.NullBooleanField(),
        ),
    ]
