# Generated by Django 3.0.7 on 2020-06-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0010_auto_20200616_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='requested_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
