# Generated by Django 3.0.7 on 2020-07-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0014_auto_20200721_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='clickthrough',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
