# Generated by Django 3.0.7 on 2020-07-21 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0015_creative_clickthrough'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creative',
            old_name='clickthrough',
            new_name='click_through',
        ),
    ]
