# Generated by Django 3.0.7 on 2020-07-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0016_auto_20200721_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creative',
            name='placement_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='creative',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
