# Generated by Django 3.0.7 on 2020-07-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0017_auto_20200728_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='markup_with_macros',
            field=models.TextField(blank=True),
        ),
    ]
