# Generated by Django 3.0.7 on 2020-08-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0019_creative_markup_without_blocking_with_macros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creative',
            name='markup_without_blocking_with_macros',
        ),
    ]
