# Generated by Django 3.0.7 on 2020-08-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0021_creative_markup_with_macros_replaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creative',
            name='markup_with_macros',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creative',
            name='markup_with_macros_replaced',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creative',
            name='markup_without_blocking',
            field=models.TextField(blank=True, null=True),
        ),
    ]
