# Generated by Django 3.0.7 on 2021-12-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0023_auto_20200805_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='concept',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creative',
            name='free_field',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
