# Generated by Django 3.0.7 on 2021-12-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0025_creative_placement_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creative',
            name='click_through',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='creative',
            name='concept',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='creative',
            name='free_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
