# Generated by Django 3.0.7 on 2020-06-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativegroup',
            name='name',
            field=models.CharField(default='Nameless Creative Group', max_length=1000),
        ),
    ]
