# Generated by Django 3.0.7 on 2020-06-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_groups', '0005_auto_20200615_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativegroup',
            name='zip',
            field=models.FileField(blank=True, upload_to='zips'),
        ),
    ]
