# Generated by Django 3.0.7 on 2021-09-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamboo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pto',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pto',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pto',
            name='start',
            field=models.DateField(),
        ),
    ]
