# Generated by Django 3.0.7 on 2021-09-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bamboo', '0002_auto_20210927_1439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coverage',
            new_name='Team',
        ),
    ]
