# Generated by Django 3.0.7 on 2021-09-27 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bamboo', '0003_auto_20210927_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pto',
            name='name',
        ),
        migrations.AddField(
            model_name='pto',
            name='team_member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to='bamboo.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pto',
            name='coverage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coverage', to='bamboo.Team'),
        ),
    ]
